import { sqliteTable, integer, text, primaryKey, uniqueIndex, index, check, type AnySQLiteColumn } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const asset_categories = sqliteTable("asset_categories", {
  category_id: integer("category_id").primaryKey({ autoIncrement: true }),
  category_name: text("category_name").notNull().unique(),
  description: text("description"),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const asset_types = sqliteTable("asset_types", {
  asset_type_id: integer("asset_type_id").primaryKey({ autoIncrement: true }),
  category_id: integer("category_id").notNull().references((): AnySQLiteColumn => asset_categories.category_id, { onDelete: "restrict" }),
  type_name: text("type_name").notNull(),
  is_active: integer("is_active").notNull().default(1),
}, (t) => [index("idx_asset_types_category_id").on(t.category_id)]);
export const asset_classes = sqliteTable("asset_classes", {
  asset_class_id: integer("asset_class_id").primaryKey({ autoIncrement: true }),
  class_name: text("class_name").notNull().unique(),
  description: text("description"),
}, (t) => []);
export const manufacturers = sqliteTable("manufacturers", {
  manufacturer_id: integer("manufacturer_id").primaryKey({ autoIncrement: true }),
  manufacturer_name: text("manufacturer_name").notNull().unique(),
  support_url: text("support_url"),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const asset_models = sqliteTable("asset_models", {
  model_id: integer("model_id").primaryKey({ autoIncrement: true }),
  manufacturer_id: integer("manufacturer_id").notNull().references((): AnySQLiteColumn => manufacturers.manufacturer_id, { onDelete: "restrict" }),
  category_id: integer("category_id").notNull().references((): AnySQLiteColumn => asset_categories.category_id, { onDelete: "restrict" }),
  asset_type_id: integer("asset_type_id").notNull().references((): AnySQLiteColumn => asset_types.asset_type_id, { onDelete: "restrict" }),
  model_name: text("model_name").notNull(),
  model_number: text("model_number"),
  default_useful_life_months: integer("default_useful_life_months"),
  is_active: integer("is_active").notNull().default(1),
}, (t) => [index("idx_asset_models_manufacturer_id").on(t.manufacturer_id), index("idx_asset_models_category_id").on(t.category_id), index("idx_asset_models_asset_type_id").on(t.asset_type_id)]);
export const asset_statuses = sqliteTable("asset_statuses", {
  status_id: integer("status_id").primaryKey({ autoIncrement: true }),
  status_code: text("status_code").notNull().unique(),
  status_name: text("status_name").notNull(),
  lifecycle_stage: text("lifecycle_stage"),
  is_terminal: integer("is_terminal").notNull().default(0),
  is_active: integer("is_active").notNull().default(1),
}, (t) => [check("no_transferred_status", sql`status_code != 'TRANSFERRED'`)]);
export const asset_conditions = sqliteTable("asset_conditions", {
  condition_id: integer("condition_id").primaryKey({ autoIncrement: true }),
  condition_code: text("condition_code").notNull().unique(),
  condition_name: text("condition_name").notNull(),
  description: text("description"),
}, (t) => []);
export const units_of_measure = sqliteTable("units_of_measure", {
  unit_of_measure_id: integer("unit_of_measure_id").primaryKey({ autoIncrement: true }),
  uom_code: text("uom_code").notNull().unique(),
  uom_name: text("uom_name").notNull(),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const movement_types = sqliteTable("movement_types", {
  movement_type_id: integer("movement_type_id").primaryKey({ autoIncrement: true }),
  movement_code: text("movement_code").notNull().unique(),
  movement_name: text("movement_name").notNull(),
  changes_location: integer("changes_location").notNull().default(1),
  changes_custody: integer("changes_custody").notNull().default(1),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const location_types = sqliteTable("location_types", {
  location_type_id: integer("location_type_id").primaryKey({ autoIncrement: true }),
  location_type_code: text("location_type_code").notNull().unique(),
  location_type_name: text("location_type_name").notNull(),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const depreciation_methods = sqliteTable("depreciation_methods", {
  depreciation_method_id: integer("depreciation_method_id").primaryKey({ autoIncrement: true }),
  method_code: text("method_code").notNull().unique(),
  method_name: text("method_name").notNull(),
  description: text("description"),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const disposal_methods = sqliteTable("disposal_methods", {
  disposal_method_id: integer("disposal_method_id").primaryKey({ autoIncrement: true }),
  method_code: text("method_code").notNull().unique(),
  method_name: text("method_name").notNull(),
  requires_certificate: integer("requires_certificate").notNull().default(1),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const business_units = sqliteTable("business_units", {
  business_unit_id: integer("business_unit_id").primaryKey({ autoIncrement: true }),
  business_unit_code: text("business_unit_code").notNull().unique(),
  business_unit_name: text("business_unit_name").notNull(),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const departments = sqliteTable("departments", {
  department_id: integer("department_id").primaryKey({ autoIncrement: true }),
  business_unit_id: integer("business_unit_id").notNull().references((): AnySQLiteColumn => business_units.business_unit_id, { onDelete: "restrict" }),
  department_code: text("department_code"),
  department_name: text("department_name").notNull(),
  is_active: integer("is_active").notNull().default(1),
}, (t) => [index("idx_departments_business_unit_id").on(t.business_unit_id)]);
export const cost_centers = sqliteTable("cost_centers", {
  cost_center_id: integer("cost_center_id").primaryKey({ autoIncrement: true }),
  department_id: integer("department_id").references((): AnySQLiteColumn => departments.department_id, { onDelete: "restrict" }),
  cost_center_code: text("cost_center_code").notNull().unique(),
  cost_center_name: text("cost_center_name").notNull(),
  is_active: integer("is_active").notNull().default(1),
}, (t) => [index("idx_cost_centers_department_id").on(t.department_id)]);
export const employees = sqliteTable("employees", {
  employee_id: integer("employee_id").primaryKey({ autoIncrement: true }),
  employee_number: text("employee_number").notNull().unique(),
  first_name: text("first_name").notNull(),
  middle_name: text("middle_name"),
  last_name: text("last_name").notNull(),
  email: text("email"),
  business_unit_id: integer("business_unit_id").references((): AnySQLiteColumn => business_units.business_unit_id, { onDelete: "restrict" }),
  department_id: integer("department_id").references((): AnySQLiteColumn => departments.department_id, { onDelete: "restrict" }),
  cost_center_id: integer("cost_center_id").references((): AnySQLiteColumn => cost_centers.cost_center_id, { onDelete: "restrict" }),
  manager_employee_id: integer("manager_employee_id").references((): AnySQLiteColumn => employees.employee_id, { onDelete: "restrict" }),
  default_location_id: integer("default_location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  employment_status: text("employment_status").notNull(),
  hire_date: text("hire_date"),
  termination_date: text("termination_date"),
  is_active: integer("is_active").notNull().default(1),
}, (t) => [index("idx_employees_business_unit_id").on(t.business_unit_id), index("idx_employees_department_id").on(t.department_id), index("idx_employees_cost_center_id").on(t.cost_center_id), index("idx_employees_manager_employee_id").on(t.manager_employee_id), index("idx_employees_default_location_id").on(t.default_location_id)]);
export const locations = sqliteTable("locations", {
  location_id: integer("location_id").primaryKey({ autoIncrement: true }),
  location_type_id: integer("location_type_id").notNull().references((): AnySQLiteColumn => location_types.location_type_id, { onDelete: "restrict" }),
  parent_location_id: integer("parent_location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  location_code: text("location_code").unique(),
  location_name: text("location_name").notNull(),
  site_code: text("site_code"),
  building: text("building"),
  floor: text("floor"),
  room_area: text("room_area"),
  rack: text("rack"),
  shelf: text("shelf"),
  bin: text("bin"),
  workstation: text("workstation"),
  rack_unit: text("rack_unit"),
  city: text("city"),
  province: text("province"),
  country: text("country"),
  vendor_id: integer("vendor_id").references((): AnySQLiteColumn => vendors.vendor_id, { onDelete: "restrict" }),
  is_active: integer("is_active").notNull().default(1),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  updated_at: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_locations_location_type_id").on(t.location_type_id), index("idx_locations_parent_location_id").on(t.parent_location_id), index("idx_locations_vendor_id").on(t.vendor_id)]);
export const assets = sqliteTable("assets", {
  revision: integer("revision").notNull().default(0),
  asset_id: integer("asset_id").primaryKey({ autoIncrement: true }),
  asset_tag: text("asset_tag").notNull().unique(),
  barcode: text("barcode").unique(),
  sku: text("sku"),
  serial_number: text("serial_number"),
  manufacturer_id: integer("manufacturer_id").references((): AnySQLiteColumn => manufacturers.manufacturer_id, { onDelete: "restrict" }),
  model_id: integer("model_id").references((): AnySQLiteColumn => asset_models.model_id, { onDelete: "restrict" }),
  category_id: integer("category_id").notNull().references((): AnySQLiteColumn => asset_categories.category_id, { onDelete: "restrict" }),
  asset_type_id: integer("asset_type_id").notNull().references((): AnySQLiteColumn => asset_types.asset_type_id, { onDelete: "restrict" }),
  asset_class_id: integer("asset_class_id").notNull().references((): AnySQLiteColumn => asset_classes.asset_class_id, { onDelete: "restrict" }),
  description: text("description"),
  status_id: integer("status_id").notNull().references((): AnySQLiteColumn => asset_statuses.status_id, { onDelete: "restrict" }),
  condition_id: integer("condition_id").notNull().references((): AnySQLiteColumn => asset_conditions.condition_id, { onDelete: "restrict" }),
  current_location_id: integer("current_location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  quantity: text("quantity").notNull().default("1"),
  unit_of_measure_id: integer("unit_of_measure_id").references((): AnySQLiteColumn => units_of_measure.unit_of_measure_id, { onDelete: "restrict" }),
  is_serialized: integer("is_serialized").notNull().default(1),
  is_active: integer("is_active").notNull().default(1),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  created_by: integer("created_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  updated_at: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  updated_by: integer("updated_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
}, (t) => [index("idx_assets_manufacturer_id").on(t.manufacturer_id), index("idx_assets_model_id").on(t.model_id), index("idx_assets_category_id").on(t.category_id), index("idx_assets_asset_type_id").on(t.asset_type_id), index("idx_assets_asset_class_id").on(t.asset_class_id), index("idx_assets_status_id").on(t.status_id), index("idx_assets_condition_id").on(t.condition_id), index("idx_assets_current_location_id").on(t.current_location_id), index("idx_assets_unit_of_measure_id").on(t.unit_of_measure_id), index("idx_assets_created_by").on(t.created_by), index("idx_assets_updated_by").on(t.updated_by), check("serialized_one", sql`is_serialized = 0 OR quantity = '1'`), index("idx_asset_serial").on(t.serial_number), check("positive_quantity", sql`CAST(quantity AS REAL) > 0`)]);
export const asset_technical_details = sqliteTable("asset_technical_details", {
  technical_id: integer("technical_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().unique().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  hostname: text("hostname"),
  mac_address: text("mac_address"),
  ip_address: text("ip_address"),
  operating_system: text("operating_system"),
  os_version: text("os_version"),
  cpu: text("cpu"),
  memory_gb: text("memory_gb"),
  storage_capacity_gb: text("storage_capacity_gb"),
  storage_type: text("storage_type"),
  bios_version: text("bios_version"),
  bios_serial: text("bios_serial"),
  device_uuid: text("device_uuid"),
  architecture: text("architecture"),
  last_inventory_scan: text("last_inventory_scan"),
  source: text("source"),
  raw_details: text("raw_details"),
  updated_at: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  updated_by: integer("updated_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
}, (t) => [index("idx_asset_technical_details_asset_id").on(t.asset_id), index("idx_asset_technical_details_updated_by").on(t.updated_by)]);
export const asset_financials = sqliteTable("asset_financials", {
  financial_id: integer("financial_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().unique().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  purchase_date: text("purchase_date"),
  purchase_price: text("purchase_price"),
  currency_code: text("currency_code"),
  vendor_id: integer("vendor_id").references((): AnySQLiteColumn => vendors.vendor_id, { onDelete: "restrict" }),
  purchase_order_id: integer("purchase_order_id").references((): AnySQLiteColumn => purchase_orders.purchase_order_id, { onDelete: "restrict" }),
  invoice_id: integer("invoice_id").references((): AnySQLiteColumn => invoices.invoice_id, { onDelete: "restrict" }),
  cost_center_id: integer("cost_center_id").references((): AnySQLiteColumn => cost_centers.cost_center_id, { onDelete: "restrict" }),
  capitalization_date: text("capitalization_date"),
  acquisition_cost: text("acquisition_cost"),
  residual_value: text("residual_value"),
  current_book_value: text("current_book_value"),
  depreciation_profile_id: integer("depreciation_profile_id").references((): AnySQLiteColumn => depreciation_profiles.depreciation_profile_id, { onDelete: "restrict" }),
  financial_classification: text("financial_classification"),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  created_by: integer("created_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  updated_at: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  updated_by: integer("updated_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
}, (t) => [index("idx_asset_financials_asset_id").on(t.asset_id), index("idx_asset_financials_vendor_id").on(t.vendor_id), index("idx_asset_financials_purchase_order_id").on(t.purchase_order_id), index("idx_asset_financials_invoice_id").on(t.invoice_id), index("idx_asset_financials_cost_center_id").on(t.cost_center_id), index("idx_asset_financials_depreciation_profile_id").on(t.depreciation_profile_id), index("idx_asset_financials_created_by").on(t.created_by), index("idx_asset_financials_updated_by").on(t.updated_by)]);
export const asset_lifecycle = sqliteTable("asset_lifecycle", {
  lifecycle_id: integer("lifecycle_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().unique().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  acquisition_date: text("acquisition_date"),
  in_service_date: text("in_service_date"),
  useful_life_months: integer("useful_life_months"),
  refresh_due_date: text("refresh_due_date"),
  end_of_life_date: text("end_of_life_date"),
  end_of_support_date: text("end_of_support_date"),
  disposal_date: text("disposal_date"),
  lifecycle_stage: text("lifecycle_stage").notNull(),
  calculated_at: text("calculated_at"),
  updated_at: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_refresh_due").on(t.refresh_due_date), index("idx_asset_lifecycle_asset_id").on(t.asset_id)]);
export const asset_assignments = sqliteTable("asset_assignments", {
  assignment_id: integer("assignment_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  employee_id: integer("employee_id").notNull().references((): AnySQLiteColumn => employees.employee_id, { onDelete: "restrict" }),
  department_id: integer("department_id").references((): AnySQLiteColumn => departments.department_id, { onDelete: "restrict" }),
  cost_center_id: integer("cost_center_id").references((): AnySQLiteColumn => cost_centers.cost_center_id, { onDelete: "restrict" }),
  location_id: integer("location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  assigned_date: text("assigned_date").notNull(),
  expected_return_date: text("expected_return_date"),
  returned_date: text("returned_date"),
  assignment_status: text("assignment_status").notNull(),
  assigned_by: integer("assigned_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  return_received_by: integer("return_received_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  assignment_notes: text("assignment_notes"),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  updated_at: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_asset_assignments_asset_id").on(t.asset_id), index("idx_asset_assignments_employee_id").on(t.employee_id), index("idx_asset_assignments_department_id").on(t.department_id), index("idx_asset_assignments_cost_center_id").on(t.cost_center_id), index("idx_asset_assignments_location_id").on(t.location_id), index("idx_asset_assignments_assigned_by").on(t.assigned_by), index("idx_asset_assignments_return_received_by").on(t.return_received_by), uniqueIndex("one_active_assignment").on(t.asset_id).where(sql`assignment_status = 'ACTIVE'`)]);
export const asset_movements = sqliteTable("asset_movements", {
  movement_id: integer("movement_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  movement_type_id: integer("movement_type_id").notNull().references((): AnySQLiteColumn => movement_types.movement_type_id, { onDelete: "restrict" }),
  from_location_id: integer("from_location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  to_location_id: integer("to_location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  from_employee_id: integer("from_employee_id").references((): AnySQLiteColumn => employees.employee_id, { onDelete: "restrict" }),
  to_employee_id: integer("to_employee_id").references((): AnySQLiteColumn => employees.employee_id, { onDelete: "restrict" }),
  movement_date: text("movement_date").notNull(),
  requested_by: integer("requested_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  approved_by: integer("approved_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  released_by: integer("released_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  received_by: integer("received_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  vendor_id: integer("vendor_id").references((): AnySQLiteColumn => vendors.vendor_id, { onDelete: "restrict" }),
  tracking_number: text("tracking_number"),
  reference_number: text("reference_number"),
  movement_status: text("movement_status").notNull(),
  remarks: text("remarks"),
  completed_at: text("completed_at"),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_asset_movements_asset_id").on(t.asset_id), index("idx_asset_movements_movement_type_id").on(t.movement_type_id), index("idx_asset_movements_from_location_id").on(t.from_location_id), index("idx_asset_movements_to_location_id").on(t.to_location_id), index("idx_asset_movements_from_employee_id").on(t.from_employee_id), index("idx_asset_movements_to_employee_id").on(t.to_employee_id), index("idx_asset_movements_requested_by").on(t.requested_by), index("idx_asset_movements_approved_by").on(t.approved_by), index("idx_asset_movements_released_by").on(t.released_by), index("idx_asset_movements_received_by").on(t.received_by), index("idx_asset_movements_vendor_id").on(t.vendor_id)]);
export const depreciation_profiles = sqliteTable("depreciation_profiles", {
  depreciation_profile_id: integer("depreciation_profile_id").primaryKey({ autoIncrement: true }),
  profile_name: text("profile_name").notNull(),
  asset_category_id: integer("asset_category_id").references((): AnySQLiteColumn => asset_categories.category_id, { onDelete: "restrict" }),
  depreciation_method_id: integer("depreciation_method_id").notNull().references((): AnySQLiteColumn => depreciation_methods.depreciation_method_id, { onDelete: "restrict" }),
  useful_life_months: integer("useful_life_months").notNull(),
  residual_percentage: text("residual_percentage").notNull(),
  convention: text("convention"),
  effective_from: text("effective_from").notNull(),
  effective_to: text("effective_to"),
  created_by: integer("created_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  is_active: integer("is_active").notNull().default(1),
}, (t) => [index("idx_depreciation_profiles_asset_category_id").on(t.asset_category_id), index("idx_depreciation_profiles_depreciation_method_id").on(t.depreciation_method_id), index("idx_depreciation_profiles_created_by").on(t.created_by)]);
export const asset_depreciation = sqliteTable("asset_depreciation", {
  depreciation_id: integer("depreciation_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  period_date: text("period_date").notNull(),
  opening_value: text("opening_value").notNull(),
  depreciation_amount: text("depreciation_amount").notNull(),
  accumulated_depreciation: text("accumulated_depreciation").notNull(),
  closing_book_value: text("closing_book_value").notNull(),
  calculation_source: text("calculation_source").notNull(),
  calculated_at: text("calculated_at").notNull(),
}, (t) => [index("idx_asset_depreciation_asset_id").on(t.asset_id), uniqueIndex("one_depreciation_per_period").on(t.asset_id,t.period_date)]);
export const vendors = sqliteTable("vendors", {
  vendor_id: integer("vendor_id").primaryKey({ autoIncrement: true }),
  vendor_code: text("vendor_code").unique(),
  vendor_name: text("vendor_name").notNull(),
  vendor_type: text("vendor_type").notNull(),
  contact_name: text("contact_name"),
  contact_email: text("contact_email"),
  contact_phone: text("contact_phone"),
  address: text("address"),
  website: text("website"),
  support_url: text("support_url"),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const purchase_orders = sqliteTable("purchase_orders", {
  purchase_order_id: integer("purchase_order_id").primaryKey({ autoIncrement: true }),
  po_number: text("po_number").notNull().unique(),
  vendor_id: integer("vendor_id").notNull().references((): AnySQLiteColumn => vendors.vendor_id, { onDelete: "restrict" }),
  order_date: text("order_date").notNull(),
  total_amount: text("total_amount"),
  currency_code: text("currency_code"),
  status: text("status").notNull(),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_purchase_orders_vendor_id").on(t.vendor_id)]);
export const purchase_order_items = sqliteTable("purchase_order_items", {
  po_item_id: integer("po_item_id").primaryKey({ autoIncrement: true }),
  purchase_order_id: integer("purchase_order_id").notNull().references((): AnySQLiteColumn => purchase_orders.purchase_order_id, { onDelete: "restrict" }),
  asset_model_id: integer("asset_model_id").references((): AnySQLiteColumn => asset_models.model_id, { onDelete: "restrict" }),
  description: text("description"),
  quantity: text("quantity").notNull().default("1"),
  unit_price: text("unit_price"),
  total_price: text("total_price"),
}, (t) => [index("idx_purchase_order_items_purchase_order_id").on(t.purchase_order_id), index("idx_purchase_order_items_asset_model_id").on(t.asset_model_id)]);
export const invoices = sqliteTable("invoices", {
  invoice_id: integer("invoice_id").primaryKey({ autoIncrement: true }),
  invoice_number: text("invoice_number").notNull(),
  vendor_id: integer("vendor_id").notNull().references((): AnySQLiteColumn => vendors.vendor_id, { onDelete: "restrict" }),
  purchase_order_id: integer("purchase_order_id").references((): AnySQLiteColumn => purchase_orders.purchase_order_id, { onDelete: "restrict" }),
  invoice_date: text("invoice_date").notNull(),
  amount: text("amount"),
  currency_code: text("currency_code"),
  file_id: integer("file_id").references((): AnySQLiteColumn => files.file_id, { onDelete: "restrict" }),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_invoices_vendor_id").on(t.vendor_id), index("idx_invoices_purchase_order_id").on(t.purchase_order_id), index("idx_invoices_file_id").on(t.file_id)]);
export const asset_warranties = sqliteTable("asset_warranties", {
  warranty_id: integer("warranty_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  provider_id: integer("provider_id").references((): AnySQLiteColumn => vendors.vendor_id, { onDelete: "restrict" }),
  warranty_start_date: text("warranty_start_date"),
  warranty_end_date: text("warranty_end_date"),
  warranty_type: text("warranty_type"),
  support_contract: text("support_contract"),
  warranty_status: text("warranty_status").notNull(),
  checked_online_at: text("checked_online_at"),
  verification_source: text("verification_source"),
  notes: text("notes"),
}, (t) => [index("idx_warranty_end").on(t.warranty_end_date), index("idx_asset_warranties_asset_id").on(t.asset_id), index("idx_asset_warranties_provider_id").on(t.provider_id)]);
export const asset_repairs = sqliteTable("asset_repairs", {
  repair_id: integer("repair_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  repair_type: text("repair_type"),
  repair_source: text("repair_source").notNull(),
  vendor_id: integer("vendor_id").references((): AnySQLiteColumn => vendors.vendor_id, { onDelete: "restrict" }),
  issue_description: text("issue_description").notNull(),
  diagnosis: text("diagnosis"),
  repair_action: text("repair_action"),
  repair_cost: text("repair_cost"),
  sent_date: text("sent_date"),
  repair_start_date: text("repair_start_date"),
  repair_complete_date: text("repair_complete_date"),
  returned_date: text("returned_date"),
  repair_status: text("repair_status").notNull(),
  technician: text("technician"),
  notes: text("notes"),
  created_by: integer("created_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_asset_repairs_asset_id").on(t.asset_id), index("idx_asset_repairs_vendor_id").on(t.vendor_id), index("idx_asset_repairs_created_by").on(t.created_by)]);
export const asset_refreshes = sqliteTable("asset_refreshes", {
  refresh_id: integer("refresh_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  recommended_date: text("recommended_date"),
  approved_date: text("approved_date"),
  completed_date: text("completed_date"),
  refresh_reason: text("refresh_reason"),
  replacement_asset_id: integer("replacement_asset_id").references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  approved_by: integer("approved_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  status: text("status").notNull(),
  notes: text("notes"),
}, (t) => [index("idx_asset_refreshes_asset_id").on(t.asset_id), index("idx_asset_refreshes_replacement_asset_id").on(t.replacement_asset_id), index("idx_asset_refreshes_approved_by").on(t.approved_by)]);
export const asset_disposals = sqliteTable("asset_disposals", {
  disposal_id: integer("disposal_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  disposal_method_id: integer("disposal_method_id").notNull().references((): AnySQLiteColumn => disposal_methods.disposal_method_id, { onDelete: "restrict" }),
  vendor_id: integer("vendor_id").references((): AnySQLiteColumn => vendors.vendor_id, { onDelete: "restrict" }),
  requested_date: text("requested_date"),
  approved_date: text("approved_date"),
  disposal_date: text("disposal_date"),
  disposal_value: text("disposal_value"),
  data_wipe_required: integer("data_wipe_required").notNull().default(1),
  data_wipe_confirmed: integer("data_wipe_confirmed").notNull().default(0),
  wiped_by: text("wiped_by"),
  wipe_date: text("wipe_date"),
  certificate_file_id: integer("certificate_file_id").references((): AnySQLiteColumn => files.file_id, { onDelete: "restrict" }),
  approved_by: integer("approved_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  status: text("status").notNull(),
  notes: text("notes"),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_asset_disposals_asset_id").on(t.asset_id), index("idx_asset_disposals_disposal_method_id").on(t.disposal_method_id), index("idx_asset_disposals_vendor_id").on(t.vendor_id), index("idx_asset_disposals_certificate_file_id").on(t.certificate_file_id), index("idx_asset_disposals_approved_by").on(t.approved_by)]);
export const users = sqliteTable("users", {
  user_id: integer("user_id").primaryKey({ autoIncrement: true }),
  employee_id: integer("employee_id").references((): AnySQLiteColumn => employees.employee_id, { onDelete: "restrict" }),
  username: text("username").notNull().unique(),
  email: text("email").notNull().unique(),
  password_hash: text("password_hash").notNull(),
  is_active: integer("is_active").notNull().default(1),
  last_login_at: text("last_login_at"),
  failed_login_count: integer("failed_login_count").notNull().default(0),
  locked_until: text("locked_until"),
  mfa_enabled: integer("mfa_enabled").notNull().default(0),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  created_by: integer("created_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  updated_at: text("updated_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_users_employee_id").on(t.employee_id), index("idx_users_created_by").on(t.created_by)]);
export const roles = sqliteTable("roles", {
  role_id: integer("role_id").primaryKey({ autoIncrement: true }),
  role_code: text("role_code").notNull().unique(),
  role_name: text("role_name").notNull(),
  description: text("description"),
  is_active: integer("is_active").notNull().default(1),
}, (t) => []);
export const permissions = sqliteTable("permissions", {
  permission_id: integer("permission_id").primaryKey({ autoIncrement: true }),
  permission_code: text("permission_code").notNull().unique(),
  module: text("module").notNull(),
  action: text("action").notNull(),
  description: text("description"),
}, (t) => []);
export const user_roles = sqliteTable("user_roles", {
  user_id: integer("user_id").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  role_id: integer("role_id").notNull().references((): AnySQLiteColumn => roles.role_id, { onDelete: "restrict" }),
  effective_from: text("effective_from"),
  effective_to: text("effective_to"),
}, (t) => [primaryKey({ columns: [t.user_id, t.role_id] }), index("idx_user_roles_user_id").on(t.user_id), index("idx_user_roles_role_id").on(t.role_id)]);
export const role_permissions = sqliteTable("role_permissions", {
  role_id: integer("role_id").notNull().references((): AnySQLiteColumn => roles.role_id, { onDelete: "restrict" }),
  permission_id: integer("permission_id").notNull().references((): AnySQLiteColumn => permissions.permission_id, { onDelete: "restrict" }),
}, (t) => [primaryKey({ columns: [t.role_id, t.permission_id] }), index("idx_role_permissions_role_id").on(t.role_id), index("idx_role_permissions_permission_id").on(t.permission_id)]);
export const user_scopes = sqliteTable("user_scopes", {
  user_scope_id: integer("user_scope_id").primaryKey({ autoIncrement: true }),
  user_id: integer("user_id").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  scope_type: text("scope_type").notNull(),
  scope_reference_id: integer("scope_reference_id"),
  access_level: text("access_level").notNull(),
  effective_from: text("effective_from"),
  effective_to: text("effective_to"),
}, (t) => [index("idx_user_scopes_user_id").on(t.user_id)]);
export const dashboard_types = sqliteTable("dashboard_types", {
  dashboard_type_id: integer("dashboard_type_id").primaryKey({ autoIncrement: true }),
  dashboard_code: text("dashboard_code").notNull().unique(),
  dashboard_name: text("dashboard_name").notNull(),
}, (t) => []);
export const user_dashboards = sqliteTable("user_dashboards", {
  user_id: integer("user_id").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  dashboard_type_id: integer("dashboard_type_id").notNull().references((): AnySQLiteColumn => dashboard_types.dashboard_type_id, { onDelete: "restrict" }),
  is_default: integer("is_default").notNull().default(1),
}, (t) => [primaryKey({ columns: [t.user_id, t.dashboard_type_id] }), index("idx_user_dashboards_user_id").on(t.user_id), index("idx_user_dashboards_dashboard_type_id").on(t.dashboard_type_id)]);
export const gate_passes = sqliteTable("gate_passes", {
  gate_pass_id: integer("gate_pass_id").primaryKey({ autoIncrement: true }),
  gate_pass_number: text("gate_pass_number").notNull().unique(),
  requester_id: integer("requester_id").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  approved_by: integer("approved_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  valid_from: text("valid_from").notNull(),
  valid_until: text("valid_until").notNull(),
  purpose: text("purpose"),
  destination: text("destination"),
  status: text("status").notNull(),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_gate_passes_requester_id").on(t.requester_id), index("idx_gate_passes_approved_by").on(t.approved_by)]);
export const gate_pass_assets = sqliteTable("gate_pass_assets", {
  gate_pass_id: integer("gate_pass_id").notNull().references((): AnySQLiteColumn => gate_passes.gate_pass_id, { onDelete: "restrict" }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
}, (t) => [primaryKey({ columns: [t.gate_pass_id, t.asset_id] }), index("idx_gate_pass_assets_gate_pass_id").on(t.gate_pass_id), index("idx_gate_pass_assets_asset_id").on(t.asset_id)]);
export const security_movements = sqliteTable("security_movements", {
  security_movement_id: integer("security_movement_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  movement_type: text("movement_type").notNull(),
  employee_id: integer("employee_id").references((): AnySQLiteColumn => employees.employee_id, { onDelete: "restrict" }),
  location_id: integer("location_id").notNull().references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  gate_pass_id: integer("gate_pass_id").references((): AnySQLiteColumn => gate_passes.gate_pass_id, { onDelete: "restrict" }),
  scanned_by: integer("scanned_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  scan_time: text("scan_time").notNull(),
  verification_result: text("verification_result").notNull(),
  flagged: integer("flagged").notNull().default(0),
  remarks: text("remarks"),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_security_movements_asset_id").on(t.asset_id), index("idx_security_movements_employee_id").on(t.employee_id), index("idx_security_movements_location_id").on(t.location_id), index("idx_security_movements_gate_pass_id").on(t.gate_pass_id), index("idx_security_movements_scanned_by").on(t.scanned_by)]);
export const inventory_sessions = sqliteTable("inventory_sessions", {
  inventory_session_id: integer("inventory_session_id").primaryKey({ autoIncrement: true }),
  session_name: text("session_name").notNull(),
  location_id: integer("location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  started_at: text("started_at").notNull(),
  completed_at: text("completed_at"),
  started_by: integer("started_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  status: text("status").notNull(),
  notes: text("notes"),
}, (t) => [index("idx_inventory_sessions_location_id").on(t.location_id), index("idx_inventory_sessions_started_by").on(t.started_by)]);
export const inventory_scan_results = sqliteTable("inventory_scan_results", {
  inventory_scan_id: integer("inventory_scan_id").primaryKey({ autoIncrement: true }),
  inventory_session_id: integer("inventory_session_id").notNull().references((): AnySQLiteColumn => inventory_sessions.inventory_session_id, { onDelete: "restrict" }),
  asset_id: integer("asset_id").references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  scanned_barcode: text("scanned_barcode"),
  scanned_at: text("scanned_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  scanned_by: integer("scanned_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  expected_location_id: integer("expected_location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  actual_location_id: integer("actual_location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  result: text("result").notNull(),
  remarks: text("remarks"),
}, (t) => [index("idx_inventory_scan_results_inventory_session_id").on(t.inventory_session_id), index("idx_inventory_scan_results_asset_id").on(t.asset_id), index("idx_inventory_scan_results_scanned_by").on(t.scanned_by), index("idx_inventory_scan_results_expected_location_id").on(t.expected_location_id), index("idx_inventory_scan_results_actual_location_id").on(t.actual_location_id)]);
export const barcode_scan_logs = sqliteTable("barcode_scan_logs", {
  scan_id: integer("scan_id").primaryKey({ autoIncrement: true }),
  barcode: text("barcode").notNull(),
  asset_id: integer("asset_id").references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  scan_type: text("scan_type").notNull(),
  scanned_by: integer("scanned_by").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  device_type: text("device_type"),
  scan_timestamp: text("scan_timestamp").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  location_id: integer("location_id").references((): AnySQLiteColumn => locations.location_id, { onDelete: "restrict" }),
  result: text("result").notNull(),
  metadata: text("metadata"),
}, (t) => [index("idx_barcode_scan_logs_asset_id").on(t.asset_id), index("idx_barcode_scan_logs_scanned_by").on(t.scanned_by), index("idx_barcode_scan_logs_location_id").on(t.location_id)]);
export const files = sqliteTable("files", {
  file_id: integer("file_id").primaryKey({ autoIncrement: true }),
  original_filename: text("original_filename").notNull(),
  stored_filename: text("stored_filename").notNull(),
  storage_path: text("storage_path").notNull(),
  mime_type: text("mime_type"),
  file_size: integer("file_size"),
  checksum: text("checksum"),
  uploaded_by: integer("uploaded_by").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  uploaded_at: text("uploaded_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
}, (t) => [index("idx_files_uploaded_by").on(t.uploaded_by)]);
export const asset_files = sqliteTable("asset_files", {
  asset_file_id: integer("asset_file_id").primaryKey({ autoIncrement: true }),
  asset_id: integer("asset_id").notNull().references((): AnySQLiteColumn => assets.asset_id, { onDelete: "restrict" }),
  file_id: integer("file_id").notNull().references((): AnySQLiteColumn => files.file_id, { onDelete: "restrict" }),
  document_type: text("document_type").notNull(),
  description: text("description"),
}, (t) => [index("idx_asset_files_asset_id").on(t.asset_id), index("idx_asset_files_file_id").on(t.file_id)]);
export const notifications = sqliteTable("notifications", {
  notification_id: integer("notification_id").primaryKey({ autoIncrement: true }),
  user_id: integer("user_id").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  notification_type: text("notification_type").notNull(),
  title: text("title").notNull(),
  message: text("message").notNull(),
  reference_type: text("reference_type"),
  reference_id: integer("reference_id"),
  is_read: integer("is_read").notNull().default(0),
  created_at: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  read_at: text("read_at"),
}, (t) => [index("idx_notifications_user_id").on(t.user_id)]);
export const audit_logs = sqliteTable("audit_logs", {
  audit_id: integer("audit_id").primaryKey({ autoIncrement: true }),
  user_id: integer("user_id").references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  event_type: text("event_type").notNull(),
  module: text("module").notNull(),
  table_name: text("table_name"),
  record_id: integer("record_id"),
  action: text("action").notNull(),
  old_values: text("old_values"),
  new_values: text("new_values"),
  ip_address: text("ip_address"),
  user_agent: text("user_agent"),
  session_id: text("session_id"),
  event_timestamp: text("event_timestamp").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ','now'))`),
  remarks: text("remarks"),
}, (t) => [index("idx_audit_logs_user_id").on(t.user_id)]);
export const app_sessions = sqliteTable("app_sessions", {
  session_hash: text("session_hash").primaryKey(),
  user_id: integer("user_id").notNull().references((): AnySQLiteColumn => users.user_id, { onDelete: "restrict" }),
  expires_at: text("expires_at").notNull(),
}, (t) => [index("idx_app_sessions_user_id").on(t.user_id)]);export const operation_guards=sqliteTable('operation_guards',{guard_id:text('guard_id').primaryKey(),passed:integer('passed').notNull()},t=>[check('operation_changed_one_row',sql`passed = 1`)]);
