import {query,one,rows,insert,audit,access,fail,guard} from './data.js';
import {now,passwordHash,random,digest} from './security.js';
export const adminTables=new Set(['users','roles','permissions','user_roles','role_permissions','user_scopes','user_permission_overrides','teams','team_members','system_settings']);
export const extraModules=['technical','warranty','repairs','refresh','disposal','custody','movements','reports','exports','settings','features','purge','barcode'];
export async function upgrade(db){
 if(await one(db,"SELECT setting_key FROM system_settings WHERE setting_key='user_module_v1'"))return;
 const st=[query(db,"UPDATE roles SET is_active=0 WHERE role_code IN ('FINANCE_ADMIN','MANAGEMENT_VIEWER','GENERAL_USER')"),query(db,"INSERT OR IGNORE INTO roles(role_code,role_name) VALUES ('SERVICE_DESK','Service Desk / Technician')"),query(db,"UPDATE roles SET role_code='ITAM_MANAGER',role_name='ITAM / Asset Manager' WHERE role_code='ITAM_TEAM'"),query(db,"UPDATE roles SET role_name='IT Administrator' WHERE role_code='IT_ADMIN'"),query(db,"UPDATE roles SET role_name='Super Admin' WHERE role_code='SUPER_ADMIN'")];
 for(const mod of extraModules)for(const action of ['view','manage'])st.push(query(db,'INSERT OR IGNORE INTO permissions(permission_code,module,action,description) VALUES (?,?,?,?)',`${mod}.${action}`,mod,action,`${action==='view'?'View':'Manage'} ${mod}`));
 st.push(query(db,"DELETE FROM role_permissions WHERE role_id IN (SELECT role_id FROM roles WHERE role_code IN ('IT_ADMIN','ITAM_MANAGER','SECURITY','SERVICE_DESK'))"));
 const grants={IT_ADMIN:['assets.view','barcode.manage','technical.view','technical.manage','warranty.view','repairs.view','repairs.manage','refresh.view','refresh.manage','movements.view','movements.manage','master.view','files.view','reports.view','exports.view'],ITAM_MANAGER:['assets.view','barcode.manage','assets.manage','technical.view','warranty.view','repairs.view','repairs.manage','refresh.view','refresh.manage','disposal.view','disposal.manage','custody.view','custody.manage','movements.view','movements.manage','inventory.view','inventory.manage','master.view','files.view','files.manage','reports.view','exports.view'],SECURITY:['assets.view','custody.view','movements.view','security.view','security.manage','barcode.manage','master.view'],SERVICE_DESK:['barcode.manage','assets.view','technical.view','warranty.view','repairs.view','repairs.manage','custody.view','master.view','files.view','reports.view']};
 for(const [role,codes]of Object.entries(grants))for(const code of codes)st.push(query(db,'INSERT OR IGNORE INTO role_permissions(role_id,permission_id) SELECT r.role_id,p.permission_id FROM roles r,permissions p WHERE r.role_code=? AND p.permission_code=?',role,code));
 st.push(query(db,"INSERT OR IGNORE INTO system_settings VALUES ('session_timeout_minutes','480')"),query(db,"INSERT OR IGNORE INTO system_settings VALUES ('user_module_v1','1')"));await db.batch(st);
}
export const safeUser=a=>a&&Object.fromEntries(Object.entries(a).filter(([k])=>!['password_hash','mfa_secret','mfa_pending_secret','mfa_last_step'].includes(k)));
async function userDetail(db,id){const a=await one(db,`SELECT u.*,e.employee_number,d.department_name,b.business_unit_name,l.location_name AS site_name FROM users u LEFT JOIN employees e ON e.employee_id=u.employee_id LEFT JOIN departments d ON d.department_id=COALESCE(u.department_id,e.department_id) LEFT JOIN business_units b ON b.business_unit_id=COALESCE(u.business_unit_id,e.business_unit_id) LEFT JOIN locations l ON l.location_id=COALESCE(u.site_id,e.default_location_id) WHERE u.user_id=?`,id);if(!a)fail('User not found.',404);return {...safeUser(a),roles:await rows(db,'SELECT r.*,ur.effective_from,ur.effective_to FROM roles r JOIN user_roles ur ON ur.role_id=r.role_id WHERE ur.user_id=?',id),scopes:await rows(db,'SELECT * FROM user_scopes WHERE user_id=?',id),overrides:await rows(db,'SELECT o.*,p.permission_code FROM user_permission_overrides o JOIN permissions p ON p.permission_id=o.permission_id WHERE o.user_id=?',id),effective_permissions:(await access(db,id))?.permissions||[]};}
const flag=(v,name)=>{if(![0,1,false,true].includes(v))fail(`Invalid ${name}.`);return Number(v);};
const text=(v,name,max=100)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>max)fail(`Enter a valid ${name}.`);return v.trim();};
async function reference(db,table,key,value){if(value===null||value==='')return null;if(!Number.isSafeInteger(Number(value))||Number(value)<1||!await one(db,`SELECT ${key} FROM ${table} WHERE ${key}=? AND is_active=1`,Number(value)))fail(`Select an active ${table.replaceAll('_',' ')} record.`);return Number(value);}
async function validated(db,input,before){const d={};for(const key of ['first_name','last_name','username','email'])if(key in input||!before)d[key]=text(input[key],key.replaceAll('_',' '),key==='email'?254:100);
 if(d.username&&!/^[\w.@+-]{3,100}$/.test(d.username))fail('Username must have 3–100 letters, digits, or . @ + - _.');if(d.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email))fail('Enter a valid email.');if(d.email)d.email=d.email.toLowerCase();if(d.username)d.username=d.username.toLowerCase();
 for(const [k,t,p] of [['employee_id','employees','employee_id'],['department_id','departments','department_id'],['business_unit_id','business_units','business_unit_id'],['site_id','locations','location_id']])if(k in input)d[k]=await reference(db,t,p,input[k]);
 for(const k of ['is_active','mfa_required','force_password_change'])if(k in input)d[k]=flag(input[k],k);
 const duplicate=await one(db,'SELECT user_id FROM users WHERE (lower(email)=? OR lower(username)=?) AND user_id<>?',d.email??before?.email,d.username??before?.username,before?.user_id??0);if(duplicate)fail('Email or username is already in use.',409);
 return d;
}
async function rolesAndScopes(db,id,d,actor,req,before){const st=[];
 if('role_ids' in d){if(!Array.isArray(d.role_ids)||d.role_ids.length>20)fail('Choose valid roles.');const ids=[...new Set(d.role_ids.map(Number))];const rs=await rows(db,'SELECT * FROM roles WHERE is_active=1');if(ids.some(i=>!rs.some(r=>r.role_id===i)))fail('Choose active roles.');const old=before?.roles||[];
 if(id===actor.user_id&&old.some(r=>r.role_code==='SUPER_ADMIN')&&!ids.some(i=>rs.find(r=>r.role_id===i)?.role_code==='SUPER_ADMIN'))fail('You cannot remove your own Super Admin role.');
 for(const r of old)if(!ids.includes(r.role_id))st.push(query(db,'DELETE FROM user_roles WHERE user_id=? AND role_id=?',id,r.role_id),audit(db,actor,'users',id,'ROLE_REMOVED',{role:r.role_code},null,req));
 for(const role of rs.filter(r=>ids.includes(r.role_id)&&!old.some(o=>o.role_id===r.role_id)))st.push(insert(db,'user_roles',{user_id:id,role_id:role.role_id}),audit(db,actor,'users',id,'ROLE_ASSIGNED',null,{role:role.role_code},req));
 }
 if('scopes' in d){if(!Array.isArray(d.scopes)||d.scopes.length>30)fail('Choose valid scopes.');const scopes=[];for(const s of d.scopes){if(!['ENTERPRISE','BUSINESS_UNIT','SITE','DEPARTMENT','TEAM','SELF','COST_CENTER'].includes(s.scope_type)||!['VIEW','MANAGE'].includes(s.access_level))fail('Invalid access scope.');const ref={BUSINESS_UNIT:['business_units','business_unit_id'],SITE:['locations','location_id'],DEPARTMENT:['departments','department_id'],TEAM:['teams','team_id'],COST_CENTER:['cost_centers','cost_center_id']}[s.scope_type];const scope_reference_id=ref?await reference(db,...ref,s.scope_reference_id):null;if(ref&&!scope_reference_id)fail('Choose a scope reference.');scopes.push({user_id:id,scope_type:s.scope_type,access_level:s.access_level,scope_reference_id});}
 st.push(query(db,'DELETE FROM user_scopes WHERE user_id=?',id),...scopes.map(s=>insert(db,'user_scopes',s)),audit(db,actor,'users',id,'SCOPE_CHANGED',before?.scopes,scopes,req));}
 if('overrides' in d){if(!Array.isArray(d.overrides)||d.overrides.length>200)fail('Invalid permission overrides.');const perms=await rows(db,'SELECT * FROM permissions'),seen=new Set(),overrides=[];for(const o of d.overrides){const permission_id=Number(o.permission_id);if(seen.has(permission_id)||!perms.some(p=>p.permission_id===permission_id)||!['ALLOW','DENY'].includes(o.effect))fail('Invalid permission override.');seen.add(permission_id);overrides.push({user_id:id,permission_id,effect:o.effect});}
 st.push(query(db,'DELETE FROM user_permission_overrides WHERE user_id=?',id),...overrides.map(o=>insert(db,'user_permission_overrides',o)),audit(db,actor,'users',id,'PERMISSION_CHANGED',before?.overrides,overrides,req));}
 return st;
}
export async function adminAPI(req,db,u,path,d){
 if(!u.super)fail('Super Admin access is required.',403);
 const method=req.method;
 if(path==='/api/admin/options'&&method==='GET'){const out={};for(const t of ['roles','permissions','business_units','departments','locations','employees','teams'])out[t]=await rows(db,`SELECT * FROM ${t} ${['permissions','roles'].includes(t)?'':'WHERE is_active=1'}`);out.role_permissions=await rows(db,'SELECT * FROM role_permissions');out.settings=await rows(db,"SELECT * FROM system_settings WHERE setting_key<>'user_module_v1'");return out;}
 if(path==='/api/admin/users'&&method==='GET'){const url=new URL(req.url),search=(url.searchParams.get('q')||'').slice(0,100),page=Math.max(1,parseInt(url.searchParams.get('page'))||1),status=url.searchParams.get('status');let where='(u.username LIKE ? OR u.email LIKE ? OR u.first_name LIKE ? OR u.last_name LIKE ?)';const args=Array(4).fill(`%${search}%`);if(['active','inactive','locked'].includes(status))where+=status==='locked'?" AND u.locked_until>strftime('%Y-%m-%dT%H:%M:%fZ','now')":` AND u.is_active=${status==='active'?1:0}`;
 const ids=await rows(db,`SELECT u.user_id FROM users u WHERE ${where} ORDER BY u.user_id DESC LIMIT 50 OFFSET ?`,...args,(page-1)*50);return{users:await Promise.all(ids.map(a=>userDetail(db,a.user_id))),total:(await one(db,`SELECT COUNT(*) n FROM users u WHERE ${where}`,...args)).n,page};}
 if(path==='/api/admin/audit'&&method==='GET'){const cursor=Number(new URL(req.url).searchParams.get('before'))||Number.MAX_SAFE_INTEGER;return{events:await rows(db,"SELECT a.*,u.username AS actor FROM audit_logs a LEFT JOIN users u ON u.user_id=a.user_id WHERE a.module IN ('users','roles','teams','system_settings') AND a.audit_id<? ORDER BY a.audit_id DESC LIMIT 100",cursor)};}
 const teamMatch=/^\/api\/admin\/teams\/(\d+)$/.exec(path);if(teamMatch&&method==='GET')return{members:await rows(db,'SELECT employee_id FROM team_members WHERE team_id=?',Number(teamMatch[1]))};
 let m=/^\/api\/admin\/users\/(\d+)(?:\/(activity|reset-password|unlock|reset-mfa))?$/.exec(path);
 if(m&&method==='GET'){if(m[2]==='activity'){const cursor=Number(new URL(req.url).searchParams.get('before'))||Number.MAX_SAFE_INTEGER;return{events:await rows(db,"SELECT a.*,u.username AS actor FROM audit_logs a LEFT JOIN users u ON u.user_id=a.user_id WHERE (a.module='users' AND a.record_id=? OR a.user_id=?) AND a.audit_id<? ORDER BY a.audit_id DESC LIMIT 100",m[1],Number(m[1]),cursor)};}return{user:await userDetail(db,Number(m[1]))};}
 if(path==='/api/admin/users'&&method==='POST'){
 const values=await validated(db,d,null);if(typeof d.temporary_password!=='string'||d.temporary_password.length<8||d.temporary_password.length>256)fail('Temporary password must have 8–256 characters.');values.password_hash=await passwordHash(d.temporary_password);values.force_password_change=d.force_password_change===false?0:1;values.created_by=u.user_id;
 // Explicit ID and atomic batch keep role, scope, account and audit creation together.
 const id=(await one(db,'SELECT COALESCE(MAX(user_id),0)+1 id FROM users')).id;const st=await rolesAndScopes(db,id,d,u,req,null);await db.batch([insert(db,'users',{...values,user_id:id}),...st,audit(db,u,'users',id,'USER_CREATED',null,safeUser(values),req)]);return{ok:true,user:await userDetail(db,id)};
 }
 if(m&&method==='POST'&&m[2]){const id=Number(m[1]),before=await userDetail(db,id);let update={},event;
 if(m[2]==='reset-password'){if(typeof d.temporary_password!=='string'||d.temporary_password.length<8||d.temporary_password.length>256)fail('Temporary password must have 8–256 characters.');update={password_hash:await passwordHash(d.temporary_password),force_password_change:1,failed_login_count:0,locked_until:null};event='PASSWORD_RESET';}
 if(m[2]==='unlock'){update={failed_login_count:0,locked_until:null};event='ACCOUNT_UNLOCKED';}
 if(m[2]==='reset-mfa'){update={mfa_enabled:0,mfa_secret:null,mfa_pending_secret:null,mfa_last_step:-1};event='MFA_RESET';}
 await db.batch([query(db,`UPDATE users SET ${Object.keys(update).map(k=>`${k}=?`).join(',')},revision=revision+1,updated_at=? WHERE user_id=? AND revision=?`,...Object.values(update),now(),id,before.revision),...guard(db),query(db,'DELETE FROM app_sessions WHERE user_id=?',id),audit(db,u,'users',id,event,safeUser(Object.fromEntries(Object.keys(update).map(k=>[k,before[k]]))),safeUser(update),req)]);return{ok:true};}
 if(m&&method==='PATCH'&&!m[2]){const id=Number(m[1]),before=await userDetail(db,id);if(Number(d.revision)!==before.revision)fail('This account changed. Reload it before saving.',409);const values=await validated(db,d,before);if(id===u.user_id&&values.is_active===0)fail('You cannot deactivate your own account.');const st=await rolesAndScopes(db,id,d,u,req,before);
 const sensitive=['role_ids','scopes','overrides','is_active','mfa_required','force_password_change'].some(k=>k in d);const event=values.is_active!==undefined&&values.is_active!==before.is_active?(values.is_active?'USER_ACTIVATED':'USER_DEACTIVATED'):'USER_UPDATED';
 await db.batch([query(db,`UPDATE users SET ${Object.keys(values).map(k=>`${k}=?,`).join('')}updated_at=?,revision=revision+1 WHERE user_id=? AND revision=?`,...Object.values(values),now(),id,before.revision),...guard(db),...st,...(sensitive?[query(db,'DELETE FROM app_sessions WHERE user_id=?',id)]:[]),audit(db,u,'users',id,event,before,safeUser(values),req)]);return{ok:true};}
 m=/^\/api\/admin\/roles(?:\/(\d+))?$/.exec(path);
 if(m&&['POST','PATCH'].includes(method)){const before=m[1]?await one(db,'SELECT * FROM roles WHERE role_id=?',Number(m[1])):null;if(m[1]&&!before)fail('Role not found.',404);if(before?.role_code==='SUPER_ADMIN')fail('Super Admin always has full access.');const role_name=text(d.role_name,'role name'),code=before?.role_code||text(d.role_code,'role code').toUpperCase();if(!/^[A-Z][A-Z0-9_]{2,49}$/.test(code)||code==='SUPER_ADMIN')fail('Invalid role code.');const all=await rows(db,'SELECT permission_id FROM permissions');if(!Array.isArray(d.permission_ids)||d.permission_ids.some(id=>!all.some(p=>p.permission_id===Number(id))))fail('Invalid permissions.');const id=before?.role_id||(await one(db,'SELECT COALESCE(MAX(role_id),0)+1 id FROM roles')).id;const previous=await rows(db,'SELECT permission_id FROM role_permissions WHERE role_id=?',id);const st=[before?query(db,'UPDATE roles SET role_name=?,is_active=? WHERE role_id=?',role_name,flag(d.is_active??1,'status'),id):insert(db,'roles',{role_id:id,role_name,role_code:code}),query(db,'DELETE FROM role_permissions WHERE role_id=?',id),...[...new Set(d.permission_ids.map(Number))].map(permission_id=>insert(db,'role_permissions',{role_id:id,permission_id})),query(db,'DELETE FROM app_sessions WHERE user_id IN (SELECT user_id FROM user_roles WHERE role_id=?)',id),audit(db,u,'roles',id,'PERMISSION_CHANGED',{role:before,permissions:previous},{role_name,permissions:d.permission_ids},req)];await db.batch(st);return{ok:true};}
 if(path==='/api/admin/teams'&&method==='POST'){const name=text(d.team_name,'team name'),id=d.team_id?await reference(db,'teams','team_id',d.team_id):(await one(db,'SELECT COALESCE(MAX(team_id),0)+1 id FROM teams')).id;const dept=await reference(db,'departments','department_id',d.department_id??null);if(!Array.isArray(d.employee_ids)||d.employee_ids.length>500)fail('Choose team members.');const members=[];for(const e of [...new Set(d.employee_ids)])members.push(await reference(db,'employees','employee_id',e));const before=await one(db,'SELECT * FROM teams WHERE team_id=?',id),oldMembers=await rows(db,'SELECT employee_id FROM team_members WHERE team_id=?',id);await db.batch([before?query(db,'UPDATE teams SET team_name=?,department_id=? WHERE team_id=?',name,dept,id):insert(db,'teams',{team_id:id,team_name:name,department_id:dept}),query(db,'DELETE FROM team_members WHERE team_id=?',id),...members.map(employee_id=>insert(db,'team_members',{team_id:id,employee_id})),audit(db,u,'teams',id,'TEAM_UPDATED',{team:before,members:oldMembers},{team_name:name,members},req)]);return{ok:true};}
 if(path==='/api/admin/features'&&method==='POST'){const features=['assets','barcode','inventory','technical','warranty','repairs','refresh','disposal','security','finance','exports'];if(!features.includes(d.feature)||typeof d.enabled!=='boolean')fail('Invalid system feature.');const key='feature:'+d.feature,before=await one(db,'SELECT * FROM system_settings WHERE setting_key=?',key);await db.batch([query(db,'INSERT INTO system_settings(setting_key,setting_value) VALUES (?,?) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value',key,d.enabled?'1':'0'),audit(db,u,'system_settings',key,'FEATURE_CHANGED',before,{enabled:d.enabled},req)]);return{ok:true};}
 if(path==='/api/admin/purge'&&method==='POST'){const tables=['asset_categories','asset_types','asset_classes','manufacturers','asset_models','asset_conditions','units_of_measure'];if(!tables.includes(d.table)||!Number.isInteger(Number(d.id)))fail('Only inactive, unreferenced master records may be purged.');const key={asset_categories:'category_id',asset_types:'asset_type_id',asset_classes:'asset_class_id',manufacturers:'manufacturer_id',asset_models:'model_id',asset_conditions:'condition_id',units_of_measure:'unit_of_measure_id'}[d.table],before=await one(db,`SELECT * FROM ${d.table} WHERE ${key}=? AND is_active=0`,Number(d.id));if(!before)fail('The record must exist and be inactive.');await db.batch([query(db,`DELETE FROM ${d.table} WHERE ${key}=? AND is_active=0`,Number(d.id)),...guard(db),audit(db,u,d.table,d.id,'RECORD_PURGED',before,null,req)]);return{ok:true};}
 if(path==='/api/admin/settings'&&method==='POST'){const timeout=Number(d.session_timeout_minutes);if(!Number.isInteger(timeout)||timeout<5||timeout>1440)fail('Session timeout must be 5–1440 minutes.');const before=await one(db,"SELECT * FROM system_settings WHERE setting_key='session_timeout_minutes'");await db.batch([query(db,"UPDATE system_settings SET setting_value=? WHERE setting_key='session_timeout_minutes'",String(timeout)),query(db,'DELETE FROM app_sessions'),audit(db,u,'system_settings','session_timeout_minutes','SETTING_CHANGED',before,{minutes:timeout},req)]);return{ok:true};}
 fail('Not found.',404);
}
