import {now,random,digest,passwordHash,verify,sessionToken} from './security.js';
import {query,one,audit,fail,guard} from './data.js';
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function newSecret(){const bytes=crypto.getRandomValues(new Uint8Array(20));let bits=0,value=0,out='';for(const b of bytes){value=(value<<8)|b;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5;}}return out;}
function decode(secret){let bits=0,value=0,out=[];for(const c of secret){value=(value<<5)|alphabet.indexOf(c);bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8;}}return new Uint8Array(out);}
export async function totp(secret,step=Math.floor(Date.now()/30000)){const counter=new Uint8Array(8);new DataView(counter.buffer).setBigUint64(0,BigInt(step));const key=await crypto.subtle.importKey('raw',decode(secret),{name:'HMAC',hash:'SHA-1'},false,['sign']);const h=new Uint8Array(await crypto.subtle.sign('HMAC',key,counter)),offset=h[19]&15;return String((new DataView(h.buffer).getUint32(offset)&0x7fffffff)%1000000).padStart(6,'0');}
export async function checkCode(secret,code,last=-1){if(!/^\d{6}$/.test(String(code)))return null;const step=Math.floor(Date.now()/30000);for(const s of [step-1,step,step+1])if(s>last&&await totp(secret,s)===String(code))return s;return null;}
async function key(env){return crypto.subtle.importKey('raw',new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(env.RENDER_API_SECRET))),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function seal(secret,env){const iv=crypto.getRandomValues(new Uint8Array(12)),data=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(env),new TextEncoder().encode(secret)));return btoa(String.fromCharCode(...iv,...data));}
export async function unseal(value,env){const bytes=Uint8Array.from(atob(value),x=>x.charCodeAt(0));return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes.slice(0,12)},await key(env),bytes.slice(12)));}
export async function securityAPI(req,db,u,path,d,env){const a=await one(db,'SELECT * FROM users WHERE user_id=?',u.user_id),tokenHash=await digest(sessionToken(req));
 if(path==='/api/auth/password'&&req.method==='POST'){if(!await verify(d.current_password||'',a.password_hash))fail('Current password is incorrect.',403);if(typeof d.new_password!=='string'||d.new_password.length<8||d.new_password.length>256)fail('Use a password of 8–256 characters.');if(await verify(d.new_password,a.password_hash))fail('Choose a different password.');await db.batch([query(db,'UPDATE users SET password_hash=?,force_password_change=0,updated_at=?,revision=revision+1 WHERE user_id=? AND revision=?',await passwordHash(d.new_password),now(),u.user_id,a.revision),...guard(db),query(db,'DELETE FROM app_sessions WHERE user_id=? AND session_hash<>?',u.user_id,tokenHash),audit(db,u,'users',u.user_id,'PASSWORD_CHANGED',{force_password_change:a.force_password_change},{force_password_change:0},req)]);return{ok:true};}
 if(path==='/api/auth/mfa/setup'&&req.method==='POST'){if(a.force_password_change)fail('Change your password first.',403);if(a.mfa_enabled)fail('MFA is already enrolled. Ask Super Admin to reset it.');const secret=newSecret();await query(db,'UPDATE users SET mfa_pending_secret=? WHERE user_id=?',await seal(secret,env),u.user_id).run();return{secret,uri:`otpauth://totp/${encodeURIComponent('jlijano-mdm:'+a.email)}?secret=${secret}&issuer=jlijano-mdm&digits=6&period=30`};}
 if(path==='/api/auth/mfa/verify'&&req.method==='POST'){if(a.force_password_change)fail('Change your password first.',403);const value=a.mfa_enabled?a.mfa_secret:a.mfa_pending_secret;if(!value)fail('Start MFA enrollment first.');const step=await checkCode(await unseal(value,env),d.code,a.mfa_last_step);if(step===null){await db.batch([query(db,'UPDATE users SET failed_login_count=failed_login_count+1,locked_until=CASE WHEN failed_login_count>=4 THEN ? ELSE locked_until END WHERE user_id=?',new Date(Date.now()+900000).toISOString(),u.user_id),audit(db,u,'users',u.user_id,'LOGIN_FAILED',null,{factor:'MFA'},req)]);fail('Authenticator code is incorrect or already used.',400);}await db.batch([query(db,'UPDATE users SET mfa_enabled=1,mfa_secret=?,mfa_pending_secret=NULL,mfa_last_step=?,failed_login_count=0,locked_until=NULL WHERE user_id=? AND mfa_last_step<?',value,step,u.user_id,step),...guard(db),query(db,'UPDATE app_sessions SET mfa_verified=1 WHERE session_hash=?',tokenHash),audit(db,u,'users',u.user_id,a.mfa_enabled?'MFA_VERIFIED':'MFA_ENROLLED',null,{mfa_enabled:1},req)]);return{ok:true};}
 fail('Not found.',404);
}
