import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../dist/server/index.js';
import {passwordHash,digest} from '../worker/security.js';
import {totp} from '../worker/mfa.js';
import {database} from './helpers.js';
test('audited user administration, permission overrides, scopes, lockout, password reset and TOTP MFA',async()=>{
 const {db,sql}=database(),env={DB:db,RENDER_API_SECRET:'test-gateway-key',SUPER_ADMIN_EMAIL:'admin@example.com',SUPER_ADMIN_PASSWORD_HASH:await passwordHash('admin-fixture')};let cookie='';
 async function call(path,method='GET',data){const r=await worker.fetch(new Request('https://fixture.example'+path,{method,headers:{'x-mdm-api-secret':env.RENDER_API_SECRET,'x-mdm-client-ip':'192.0.2.1',cookie},body:data===undefined?undefined:JSON.stringify(data)}),env);if(r.headers.has('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,...await r.json()};}
 async function login(email='admin@example.com',password='admin-fixture'){cookie='';const r=await call('/api/auth/login','POST',{email,password});assert.equal(r.status,200,r.message);return r;}
 await login();const adminCookie=cookie,options=await call('/api/admin/options'),role=code=>options.roles.find(r=>r.role_code===code).role_id,perm=code=>options.permissions.find(p=>p.permission_code===code).permission_id;
 assert.ok(role('SERVICE_DESK'));assert.equal(options.role_permissions.some(x=>x.role_id===role('IT_ADMIN')&&x.permission_id===perm('finance.view')),false);
 async function create(username,role_ids,scopes=[{scope_type:'ENTERPRISE',access_level:'MANAGE'}],extra={}){cookie=adminCookie;const r=await call('/api/admin/users','POST',{first_name:'Test',last_name:'Account',username,email:username+'@example.com',temporary_password:'temporary-fixture',role_ids,scopes,...extra});assert.equal(r.status,200,r.message);return r.user;}
 let tech=await create('technician',[role('IT_ADMIN')]);assert.equal(tech.force_password_change,1);assert(!JSON.stringify(tech).includes('password_hash'));const signed=await login('technician','temporary-fixture');assert.equal(signed.redirect,'/account-security');assert.equal((await call('/api/records/assets')).status,403);assert.equal((await call('/api/auth/password','POST',{current_password:'wrong',new_password:'permanent-fixture'})).status,403);assert.equal((await call('/api/auth/password','POST',{current_password:'temporary-fixture',new_password:'permanent-fixture'})).status,200);
 assert.equal((await call('/api/records/asset_financials')).status,403);assert.equal((await call('/api/records/asset_technical_details')).status,200);assert.equal((await call('/api/admin/users')).status,403);assert.equal((await call('/api/records/users')).status,403);
 const oldCookie=cookie;cookie=adminCookie;tech=(await call('/api/admin/users/'+tech.user_id)).user;assert.equal((await call('/api/admin/users/'+tech.user_id,'PATCH',{revision:tech.revision,role_ids:[role('IT_ADMIN'),role('SERVICE_DESK')],overrides:[{permission_id:perm('technical.manage'),effect:'DENY'},{permission_id:perm('finance.view'),effect:'ALLOW'}]})).status,200);
 cookie=oldCookie;assert.equal((await call('/api/auth/me')).status,401);await login('technician','permanent-fixture');const user=(await call('/api/auth/me')).user;assert(!user.permissions.includes('technical.manage'));assert(user.permissions.includes('finance.view'));assert.equal((await call('/api/records/asset_financials')).status,200);
 cookie=adminCookie;tech=(await call('/api/admin/users/'+tech.user_id)).user;assert.equal((await call('/api/admin/users/'+tech.user_id,'PATCH',{revision:tech.revision,is_active:0})).status,200);cookie='';assert.equal((await call('/api/auth/login','POST',{email:'technician',password:'permanent-fixture'})).status,401);
 cookie=adminCookie;tech=(await call('/api/admin/users/'+tech.user_id)).user;assert.equal((await call('/api/admin/users/'+tech.user_id,'PATCH',{revision:tech.revision,is_active:1})).status,200);await call('/api/admin/users/'+tech.user_id+'/unlock','POST',{});for(let i=0;i<5;i++){cookie='';assert.equal((await call('/api/auth/login','POST',{email:'technician',password:'wrong-fixture'})).status,401);}assert.equal((await call('/api/auth/login','POST',{email:'technician',password:'permanent-fixture'})).status,429);
 cookie=adminCookie;assert.equal((await call('/api/admin/users/'+tech.user_id+'/unlock','POST',{})).status,200);assert.equal((await call('/api/admin/users/'+tech.user_id+'/reset-password','POST',{temporary_password:'reset-fixture'})).status,200);await login('technician','reset-fixture');assert.equal((await call('/api/metadata')).status,403);assert.equal((await call('/api/auth/password','POST',{current_password:'reset-fixture',new_password:'permanent-fixture-2'})).status,200);
 cookie=adminCookie;let mfa=await create('mfauser',[role('SECURITY')],undefined,{force_password_change:false,mfa_required:true});await login('mfauser','temporary-fixture');assert.equal((await call('/api/metadata')).status,403);const setup=await call('/api/auth/mfa/setup','POST',{});assert.equal(setup.status,200);const enrolled=await call('/api/auth/mfa/verify','POST',{code:await totp(setup.secret)});assert.equal(enrolled.status,200,enrolled.message);assert.equal((await call('/api/metadata')).status,200);assert.equal((await call('/api/records/asset_technical_details')).status,403);assert.equal((await call('/api/records/assets','POST',{})).status,403);assert.equal((await call('/api/auth/mfa/verify','POST',{code:await totp(setup.secret)})).status,400);assert(!sql.prepare('SELECT mfa_secret FROM users WHERE user_id=?').get(mfa.user_id).mfa_secret.includes(setup.secret));
 cookie=adminCookie;const activity=await call('/api/admin/users/'+tech.user_id+'/activity');for(const event of ['USER_CREATED','ROLE_ASSIGNED','PERMISSION_CHANGED','USER_DEACTIVATED','USER_ACTIVATED','PASSWORD_RESET','ACCOUNT_UNLOCKED','LOGIN_FAILED'])assert(activity.events.some(a=>a.action===event),event);assert(activity.events.every(a=>a.ip_address==='192.0.2.1'));assert(!JSON.stringify(activity).includes('temporary-fixture'));assert(!JSON.stringify(activity).includes('pbkdf2:'));
 const team=await call('/api/admin/teams','POST',{team_name:'Team A',employee_ids:[]});assert.equal(team.status,200,team.message);const teamID=sql.prepare('SELECT team_id FROM teams').get().team_id;tech=(await call('/api/admin/users/'+tech.user_id)).user;assert.equal((await call('/api/admin/users/'+tech.user_id,'PATCH',{revision:tech.revision,scopes:[{scope_type:'TEAM',scope_reference_id:teamID,access_level:'VIEW'}]})).status,200);await login('technician','permanent-fixture-2');assert.equal((await call('/api/records/assets')).rows.length,0);
 cookie=adminCookie;
 const bu=(await call('/api/records/business_units','POST',{business_unit_code:'B1',business_unit_name:'Unit One'})).id;
 const dept=(await call('/api/records/departments','POST',{department_code:'D1',department_name:'Department One',business_unit_id:bu})).id;
 const site=(await call('/api/records/locations','POST',{location_name:'Iloilo',location_type_id:2})).id,other=(await call('/api/records/locations','POST',{location_name:'Other Site',location_type_id:2})).id;
 const emp=(await call('/api/records/employees','POST',{employee_number:'E1',first_name:'Team',last_name:'Member',employment_status:'ACTIVE',default_location_id:site,business_unit_id:bu,department_id:dept})).id;
 assert.equal((await call('/api/admin/teams','POST',{team_id:teamID,team_name:'Team A',department_id:dept,employee_ids:[emp]})).status,200);
 const asset=(await call('/api/records/assets','POST',{asset_tag:'Scope Asset',barcode:'SCOPE-1',category_id:1,asset_type_id:1,asset_class_id:1,condition_id:1,current_location_id:site})).id;
 const hidden=(await call('/api/records/assets','POST',{asset_tag:'Outside Scope',category_id:1,asset_type_id:1,asset_class_id:1,condition_id:1,current_location_id:other})).id;
 assert.equal((await call(`/api/assets/${asset}/actions/assign`,'POST',{employee_id:emp,location_id:site})).status,200);
 await login('technician','permanent-fixture-2');assert.deepEqual((await call('/api/records/assets')).rows.map(a=>a.asset_id),[asset]);assert.equal((await call('/api/records/assets/'+hidden)).rows.length,0);assert.equal((await call('/api/assets/'+hidden+'/context')).status,404);assert.equal((await call('/api/lookups/employees')).rows.length,1);assert.equal((await call('/api/export/assets')).csv.includes('Outside Scope'),false);
 for(const scope of [{scope_type:'SITE',scope_reference_id:site},{scope_type:'DEPARTMENT',scope_reference_id:dept},{scope_type:'BUSINESS_UNIT',scope_reference_id:bu},{scope_type:'SELF'}]){cookie=adminCookie;tech=(await call('/api/admin/users/'+tech.user_id)).user;assert.equal((await call('/api/admin/users/'+tech.user_id,'PATCH',{revision:tech.revision,employee_id:emp,scopes:[{...scope,access_level:'VIEW'}]})).status,200);await login('technician','permanent-fixture-2');assert.deepEqual((await call('/api/records/assets')).rows.map(a=>a.asset_id),[asset]);}
 cookie=adminCookie;const root=(await call('/api/admin/users/1')).user;assert.equal((await call('/api/admin/users/1','PATCH',{revision:root.revision,is_active:0})).status,400);assert.equal((await call('/api/admin/users/1','PATCH',{revision:root.revision,role_ids:[]})).status,400);assert.equal((await call('/api/admin/roles/'+role('SUPER_ADMIN'),'PATCH',{role_name:'Changed',permission_ids:[]})).status,400);
 assert.equal((await call('/api/admin/features','POST',{feature:'technical',enabled:false})).status,200);await login('technician','permanent-fixture-2');assert.equal((await call('/api/records/asset_technical_details')).status,403);
 cookie=adminCookie;assert.equal((await call('/api/admin/settings','POST',{session_timeout_minutes:15})).status,200);assert.equal((await call('/api/auth/me')).status,401);await login();const hash=await digest(cookie.split('=')[1]),expires=sql.prepare('SELECT expires_at FROM app_sessions WHERE session_hash=?').get(hash).expires_at;assert(Date.parse(expires)-Date.now()<15*60000+1000);sql.prepare('UPDATE app_sessions SET expires_at=? WHERE session_hash=?').run('2000-01-01T00:00:00Z',hash);assert.equal((await call('/api/auth/me')).status,401);
});
